// src/app/pages/public/login-page/login-page.component.ts
import { InputPasswordComponent } from './../../../components/inputs/input-password/input-password.component';
import { Component, effect } from '@angular/core';

import {
  FormControl,
  FormGroup,
  FormsModule,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { ImgTopComponent } from '../../../components/img-top/img-top.component';
import { InputIconModule } from 'primeng/inputicon';
import { IconFieldModule } from 'primeng/iconfield';
import { InputTextModule } from 'primeng/inputtext';
import { InputGroupModule } from 'primeng/inputgroup';
import { InputGroupAddonModule } from 'primeng/inputgroupaddon';
import { PasswordModule } from 'primeng/password';
import { AuthService } from 'src/app/service/auth/auth.service';
import { ButtonModule } from 'primeng/button';
import { MessageModule } from 'primeng/message';
import { ToastModule } from 'primeng/toast';
import { MessageService } from 'primeng/api';
import { DataFormService } from 'src/app/service/utils/data-form.service';

@Component({
  selector: 'app-login-page',
  standalone: true,
  imports: [
    MessageModule,
    PasswordModule,
    InputGroupModule,
    InputGroupAddonModule,
    ButtonModule,
    FormsModule,
    ImgTopComponent,
    RouterLink,
    InputIconModule,
    IconFieldModule,
    InputTextModule,
    InputPasswordComponent,
    ReactiveFormsModule,
    ToastModule,
  ],
  providers: [Validators, AuthService, MessageService],
  templateUrl: './login-page.component.html',
  styleUrl: './login-page.component.scss',
})
export class LoginPageComponent {
  onVisual = false;
  loader = true;
  showPassword = false;

  formLogin: FormGroup = new FormGroup({
    username: new FormControl('', [Validators.required]),
    password: new FormControl('', [Validators.required]),
  });

  constructor(
    private readonly _authService: AuthService,
    private _messageService: MessageService,
    private _dataFormService: DataFormService,
    private router: Router
  ) {}

  togglePasswordVisibility() {
    this.showPassword = !this.showPassword;
  }

  login() {
    const user = this.formLogin.value;

    this._authService.signIn(user);



  }
  changeVisual() {
    this.onVisual = !this.onVisual;
    console.log(this.onVisual);
  }
}

@if (loading()) {
  <app-spinner></app-spinner>
} @else {
  <section class="flex flex-col h-screen">
    <!-- <div class="img-top"></div> -->

    <!-- Imagen superior de la pagina -->
    <app-img-top></app-img-top>

    <!-- Logo y formulario de login -->
    <div class="flex flex-col items-center h-full justify-center">
      <img src="../../../assets/images/Logo.svg" alt="logo" />

      <!-- Formulario -->
      <div
        class="flex flex-col m-5 bg-white rounded-md items-center shadow-lg border-gray-200 border-solid border-[0.2px] p-5">
        <h3>Inicia sesión para continuar</h3>
        <form
          class="flex flex-col items-center gap-5 mb-4"
          [formGroup]="formLogin">
          <!-- Input correo -->
          <div class="flex flex-col gap-1 w-full">
            <span class="text-gray-700"
              >Nombre de usuario:<span class="text-red-500">*</span></span
            >
            <p-inputgroup>
              <p-inputgroup-addon>
                <i class="pi pi-user"></i>
              </p-inputgroup-addon>
              <input
                pInputText
                placeholder="Ingrese nombre de usuario"
                formControlName="username" />
            </p-inputgroup>

            @if (
              formLogin.get('username')?.hasError('required') &&
              formLogin.get('username')?.touched
            ) {
              <p-message severity="error" variant="simple" size="small"
                >El nombre de usuario no puede estar vació</p-message
              >
            }
            <!-- @if (formLogin.get("email")?.errors?.['pattern']&&
            formLogin.get("email")?.touched) {
            <p-message severity="error" variant="simple" size="small"
              >El correo es invalido</p-message
            >
            } -->
          </div>
          <div class="flex flex-col gap-1 w-full">
            <span class="text-gray-700"
              >Contraseña:<span class="text-red-500">*</span></span
            >
            <app-input-password
              formControlName="password"
              [placeholder]="'Ingresa tu contraseña'"
              [control]="formLogin.get('password')"></app-input-password>
          </div>
          <p-button
            [disabled]="formLogin.invalid"
            label="Ingresar"
            type="submit"
            (onClick)="login()" />
        </form>
        <a routerLink="*">¿Olvidaste tu contraseña?</a>
        <a routerLink="*">¿Olvidaste tu usuario?</a>
      </div>
      <a routerLink="/register-page" class="w-60 text-center"
        >¿Aun no tienes una cuenta? Regístrate</a
      >
    </div>
  </section>
  <div class="card flex justify-center">

  </div>
}
<p-toast />

// src/pages/login-page/LoginPage.jsx
import { Input } from "../../components/input/Input"

export const LoginPage = () => {
  return (
    <>
      <section className="flex relative flex-col justify-center items-center w-screen h-screen p-6">
        <img src="/src/assets/images/Logo.svg" alt="logo" />
        <div className=" shadow-lg  max-w-96  min-w-72 h-80 rounded-lg p-2 flex flex-col items-center gap-5 border-0.5 border-red-main">
          <h3 className="text-medium-font text-gray-500">Inicia sesión para continuar</h3>
          <form action="" className="flex flex-col items-center w-full gap-4">
            <Input placeholder={"Ingrese su usuario"} label={"Usuario"} icon={"pi pi-user"}></Input>
            <Input placeholder={"Ingrese su contraseña"} label={"Conreaseña"} icon={"pi pi-key"}></Input>
            <button className="bg-red-main rounded-sm w-28 h-9 text-white shadow-md">Ingresar</button>
          </form >
          <a href="#" className="w-52 text-secundari-font text-center underline">¿Aun no tienes una cuenta? Registrate?</a>
        </div >
      </section >
    </>
  )
}
